name: Combine Textures & Generate Item JSON

on:
  workflow_dispatch:
  push:
    paths:
      - 'parts/*.png'
      - '.github/workflows/combine_textures_and_json.yml'
      - 'combine_textures_and_json.py'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Pillow
      run: pip install Pillow

    - name: Generate textures and item json
      run: python combine_textures_and_json.py

    - name: Commit and push results
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto: Generate textures & item json"
        file_pattern: |
          Resourcepack/textures/item/*.png
          behavior_pack/items/*.json
